# Generated by Django 4.2.4 on 2023-09-26 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_short', models.CharField(blank=True, max_length=24)),
                ('markup', models.DecimalField(decimal_places=5, default=1, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=5, default=1, max_digits=10)),
                ('vat', models.DecimalField(decimal_places=2, default=1, max_digits=3)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(db_index=True, unique=True)),
                ('article', models.CharField(max_length=24)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=24)),
                ('description', models.TextField(blank=True)),
                ('initial_qua', models.IntegerField(default=0)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_supplied', models.BooleanField(default=True)),
                ('is_promo', models.BooleanField(default=False)),
                ('markup', models.DecimalField(decimal_places=5, default=1, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=5, default=1, max_digits=10)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.brands')),
            ],
        ),
    ]
