# Generated by Django 4.2.4 on 2023-10-06 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_tagsproducts_alter_products_options_products_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brand_prod', to='stock.brands'),
        ),
    ]
