# Generated by Django 4.2.4 on 2023-10-10 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0003_alter_products_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'ordering': ['name'], 'verbose_name': 'Марка', 'verbose_name_plural': 'Марки'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='tagsproducts',
            options={'ordering': ['tag'], 'verbose_name': 'Тег товара', 'verbose_name_plural': 'Теги товаров'},
        ),
        migrations.AddField(
            model_name='products',
            name='author',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
