# Generated by Django 4.2.4 on 2023-11-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_brands_author_historicalbrands_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbrands',
            name='time_create',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
