# Generated by Django 4.2.4 on 2023-11-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_alter_brands_time_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbrands',
            name='time_update',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
