# Generated by Django 4.2.4 on 2023-11-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_alter_brands_time_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproducts',
            name='photo',
            field=models.TextField(blank=True, default='/stock/images/skincare_icon.png', max_length=100, null=True, verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='products',
            name='photo',
            field=models.ImageField(blank=True, default='/stock/images/skincare_icon.png', null=True, upload_to='product_photos/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
