# Generated by Django 4.2.4 on 2023-11-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_historicalprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/images/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
